- title: Editorial Services
  type: service
  contents:
    - year: 2024 - Now
      role: Area Chair
      venue: Advances in Neural Information Processing Systems (NeurIPS)
      venue_url: 
    - year: 2024
      role: Guest editor
      venue: Journal of Nonlinear & Variational Analysis
      venue_url: 
    - year: 2022 - Now
      role: Associate Editor
      venue: Journal of Applied and Numerical Optimization
      venue_url: 

- title: Conference/Journal Referees
  type: review
  contents:
    - title: Conferences
      description:
        - International Conference on Machine Learning (<b>ICML</b>)
        - International Conference on Learning Representations (<b>ICLR</b>)
        - Conference on Neural Information Processing Systems (<b>NeurIPS</b>)
    - title: SIAM
      description:
        - SIAM Journal on Optimization
        - SIAM Journal on Imaging Sciences
        - SIAM Journal on Scientific Computing
    - title: Springer
      description:
        - Mathematical Programming
        - Journal of Global Optimization
        - Journal of Optimization Theory and Applications
        - Journal of Mathematical Imaging and Vision
        - Numerical Algorithm
        - Computational Optimization and Applications
        - Applied Mathematics and Optimization
        - Journal of Global Optimization
        - Optimization Letter
        - Set-Valued and Variational Analysis
        - Journal of Scientific Computing
        - Statistics and Computing
    - title: Elsevier
      description:
        - Applied and Computational Harmonic Analysis
        - Applied Mathematics and Computation
        - Applied Mathematical Modeling
        - Computers and Mathematics with Applications
        - Journal of Computational and Applied Mathematics
        - Signal Processing
    - title: Informs
      description:
        - Mathematics of Operations Research
    - title: IEEE 
      description:
        - IEEE Trans. on Image Processing
        - IEEE Trans. on Signal Processing
    - title: IMA 
      description:
        - IMA Journal of Numerical Analysis
    - title: Taylor & Francis
      description:
        - Optimization
        - Optimization Methods and Software
    - title: AIMS
      description:
        - Inverse Problems and Imaging
        - Journal of Computational Mathematics
    - title: Other journals
      description:
        - ESAIM:&nbsp;ControlOptimization and Calculus of Variations
        - Communication in Mathematical Sciences
        - Advances in Computational Mathematics
        - Computational Optimization and Applications
